# Generated by Django 4.2.24 on 2025-10-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='کد درس')),
                ('course_name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('credit_hours', models.PositiveIntegerField(default=3, verbose_name='تعداد واحد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField(unique=True, verbose_name='شماره طبقه')),
                ('floor_name', models.CharField(max_length=50, verbose_name='نام طبقه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'طبقه',
                'verbose_name_plural': 'طبقات',
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل استاد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='شماره اتاق')),
                ('room_type', models.CharField(choices=[('classroom', 'کلاس درس'), ('lab', 'آزمایشگاه'), ('office', 'دفتر'), ('study_hall', 'سالن مطالعه'), ('other', 'سایر')], default='classroom', max_length=20, verbose_name='نوع اتاق')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('position', models.CharField(choices=[('left', 'سمت چپ راهرو'), ('right', 'سمت راست راهرو'), ('center', 'وسط راهرو')], default='left', max_length=10, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='classes.floor', verbose_name='طبقه')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
                'ordering': ['floor__floor_number', 'room_number'],
                'unique_together': {('floor', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه'), ('friday', 'جمعه')], max_length=15, verbose_name='روز هفته')),
                ('time_slot', models.CharField(choices=[('08:00', 'کلاس\u200cهای 8 صبح'), ('10:30', 'کلاس\u200cهای 10:30'), ('13:30', 'کلاس\u200cهای 13:30'), ('16:30', 'کلاس\u200cهای 16:30')], max_length=10, verbose_name='زمان')),
                ('semester', models.CharField(blank=True, max_length=20, null=True, verbose_name='نیمسال')),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True, verbose_name='سال تحصیلی')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.course', verbose_name='درس')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.room', verbose_name='اتاق')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='classes.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'برنامه کلاسی',
                'verbose_name_plural': 'برنامه\u200cهای کلاسی',
                'ordering': ['day_of_week', 'time_slot', 'room__floor__floor_number'],
                'unique_together': {('room', 'day_of_week', 'time_slot')},
            },
        ),
    ]
