# Generated by Django 4.2.24 on 2025-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='is_holding',
            field=models.BooleanField(default=True, help_text='آیا این کلاس برگزار می\u200cشود؟', verbose_name='برگزار می\u200cشود'),
        ),
    ]
