# Generated by Django 4.2.24 on 2025-10-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classschedule_is_holding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='is_holding',
            field=models.BooleanField(default=True, help_text='آیا این کلاس در حال حاضر برگزار می\u200cشود؟', verbose_name='کلاس برگزار می\u200cشود'),
        ),
    ]
