# Generated by Django 4.2.24 on 2025-10-01 19:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classschedule_is_holding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='classes.teacher', verbose_name='استاد مرتبط')),
            ],
            options={
                'verbose_name': 'کاربر استاد',
                'verbose_name_plural': 'کاربران استاد',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='EducationalConsultingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جلسه')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع مشاوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('session_date', models.DateField(verbose_name='تاریخ جلسه')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('max_participants', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='حداکثر تعداد شرکت\u200cکنندگان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('cancelled', 'لغو شده'), ('completed', 'تکمیل شده')], default='active', max_length=20, verbose_name='وضعیت جلسه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_sessions', to=settings.AUTH_USER_MODEL, verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'جلسه مشاوره آموزشی',
                'verbose_name_plural': 'جلسات مشاوره آموزشی',
                'ordering': ['-session_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='کد دانشجویی')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کاربر دانشجو',
                'verbose_name_plural': 'کاربران دانشجو',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='SessionRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'ثبت\u200cنام شده'), ('cancelled', 'لغو شده'), ('attended', 'حاضر شده'), ('absent', 'غایب')], default='registered', max_length=20, verbose_name='وضعیت ثبت\u200cنام')),
                ('registration_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای ثبت\u200cنام')),
                ('teacher_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای استاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='classes.educationalconsultingsession', verbose_name='جلسه مشاوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to='classes.studentuser', verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام جلسه مشاوره',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای جلسات مشاوره',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
