# Generated by Django 4.2.24 on 2025-10-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_teacheruser_educationalconsultingsession_studentuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalconsultingsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting_sessions', to='classes.teacheruser', verbose_name='استاد'),
        ),
    ]
