# Generated by Django 4.2.24 on 2025-10-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_educationalconsultingsession_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='time_slot',
            field=models.CharField(choices=[('07:30-09:15', '7:30-9:15'), ('09:15-11:00', '9:15-11:00'), ('11:00-13:15', '11:00-13:15'), ('13:15-15:00', '13:15-15:00'), ('15:00-16:45', '15:00-16:45'), ('16:45-18:00', '16:45-18:00'), ('07:30-10:10', '7:30-10:10'), ('10:15-13:30', '10:15-13:30'), ('13:30-16:00', '13:30-16:00'), ('16:00-18:30', '16:00-18:30')], max_length=15, verbose_name='زمان'),
        ),
    ]
