# Generated by Django 4.2.24 on 2025-10-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classschedule_time_slot'),
    ]

    operations = [
    ]
