# Generated by Django 4.2.24 on 2025-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20251006_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تخصص'),
        ),
    ]
