# Generated by Django 4.2.24 on 2025-10-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_rename_phone_teacher_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionregistration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessionregistration',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessionregistration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='EducationalConsultingSession',
        ),
        migrations.DeleteModel(
            name='SessionRegistration',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='TeacherUser',
        ),
    ]
