# Generated by Django 4.2.24 on 2025-10-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_faculty_course_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['faculty', 'floor_number'], 'verbose_name': 'طبقه', 'verbose_name_plural': 'طبقات'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['faculty', 'floor__floor_number', 'room_number'], 'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['faculty', 'full_name'], 'verbose_name': 'استاد', 'verbose_name_plural': 'اساتید'},
        ),
        migrations.AddField(
            model_name='floor',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='classes.faculty', verbose_name='دانشکده'),
        ),
        migrations.AddField(
            model_name='room',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='classes.faculty', verbose_name='دانشکده'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='classes.faculty', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.PositiveIntegerField(verbose_name='شماره طبقه'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('faculty', 'floor_number')},
        ),
    ]
