# Generated by Django 4.2.24 on 2025-10-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_floor_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_image',
            field=models.CharField(blank=True, help_text='نام فایل تصویر در پوشه static/images/ (مثال: AI.jpg)', max_length=200, null=True, verbose_name='نام فایل تصویر'),
        ),
    ]
