# Generated by Django 4.2.24 on 2025-10-11 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_faculty_faculty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='not_holding_reported_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که دانشجویان گزارش عدم برگزاری دادند', null=True, verbose_name='زمان گزارش عدم برگزاری'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='student_reported_not_holding',
            field=models.BooleanField(default=False, help_text='آیا دانشجویان گزارش کرده\u200cاند که کلاس برگزار نمی\u200cشود؟', verbose_name='دانشجویان گزارش عدم برگزاری داده\u200cاند'),
        ),
        migrations.CreateModel(
            name='ClassCancellationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_identifier', models.CharField(max_length=255, verbose_name='شناسه رای\u200cدهنده')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رای')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_votes', to='classes.classschedule', verbose_name='برنامه کلاسی')),
            ],
            options={
                'verbose_name': 'رای لغو کلاس',
                'verbose_name_plural': 'رای\u200cهای لغو کلاس',
                'ordering': ['-voted_at'],
                'unique_together': {('schedule', 'voter_identifier')},
            },
        ),
    ]
