# Generated by Django 4.2.24 on 2025-10-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_classschedule_not_holding_reported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='holding_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که دانشجویان تأیید برگزاری دادند', null=True, verbose_name='زمان تأیید برگزاری'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='student_reported_holding',
            field=models.BooleanField(default=False, help_text='آیا دانشجویان تأیید کرده\u200cاند که کلاس برگزار می\u200cشود؟', verbose_name='دانشجویان تأیید برگزاری داده\u200cاند'),
        ),
        migrations.CreateModel(
            name='ClassConfirmationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_identifier', models.CharField(max_length=255, verbose_name='شناسه رای\u200cدهنده')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رای')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_votes', to='classes.classschedule', verbose_name='برنامه کلاسی')),
            ],
            options={
                'verbose_name': 'رای تأیید برگزاری کلاس',
                'verbose_name_plural': 'رای\u200cهای تأیید برگزاری کلاس',
                'ordering': ['-voted_at'],
                'unique_together': {('schedule', 'voter_identifier')},
            },
        ),
    ]
