# Generated by Django 4.2.24 on 2025-10-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_classschedule_holding_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['day_of_week', 'start_time', 'room__floor__floor_number'], 'verbose_name': 'برنامه کلاسی', 'verbose_name_plural': 'برنامه\u200cهای کلاسی'},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(blank=True, help_text='ساعت پایان کلاس (مثال: 09:15)', null=True, verbose_name='ساعت پایان'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(blank=True, help_text='ساعت شروع کلاس (مثال: 07:30)', null=True, verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('07:30-09:15', '7:30-9:15'), ('09:15-11:00', '9:15-11:00'), ('11:00-13:15', '11:00-13:15'), ('13:15-15:00', '13:15-15:00'), ('15:00-16:45', '15:00-16:45'), ('16:45-18:00', '16:45-18:00'), ('07:30-10:10', '7:30-10:10'), ('10:15-13:30', '10:15-13:30'), ('13:30-16:00', '13:30-16:00'), ('16:00-18:30', '16:00-18:30')], help_text='بازه زمانی قدیمی - به صورت خودکار از ساعت شروع و پایان محاسبه می\u200cشود', max_length=15, null=True, verbose_name='بازه زمانی (قدیمی)'),
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('room', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
