# Generated by Django 4.2.24 on 2025-10-15 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_parse_time_slot_to_start_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=32, verbose_name='نیمسال')),
                ('academic_year', models.CharField(max_length=32, verbose_name='سال تحصیلی')),
                ('source_filename', models.CharField(max_length=255, verbose_name='نام فایل منبع')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='تعداد کل')),
                ('inserted', models.PositiveIntegerField(default=0, verbose_name='تعداد افزوده\u200cشده')),
                ('updated', models.PositiveIntegerField(default=0, verbose_name='تعداد بروزرسانی\u200cشده')),
                ('errors_json', models.JSONField(blank=True, default=list, verbose_name='خطاها')),
                ('dry_run', models.BooleanField(default=True, verbose_name='اجرای آزمایشی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'انجام شد'), ('failed', 'ناموفق')], default='pending', max_length=16, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='classes.faculty', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'لاگ درون\u200cریزی',
                'verbose_name_plural': 'لاگ\u200cهای درون\u200cریزی',
                'ordering': ['-created_at'],
            },
        ),
    ]
