# Generated by Django 4.2.24 on 2025-10-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_importjob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classconfirmationvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classconfirmationvote',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='holding_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='not_holding_reported_at',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='student_reported_holding',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='student_reported_not_holding',
        ),
        migrations.DeleteModel(
            name='ClassCancellationVote',
        ),
        migrations.DeleteModel(
            name='ClassConfirmationVote',
        ),
    ]
