# Generated by Django 4.2.24 on 2025-10-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_remove_voting_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
    ]
