# Generated by Django 4.2.24 on 2025-11-01 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0019_remove_capacity_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تبلیغ')),
                ('image', models.ImageField(help_text='تصویر تبلیغ به صورت full-bleed نمایش داده می\u200cشود', upload_to='ads/', verbose_name='تصویر تبلیغ')),
                ('link', models.URLField(help_text='لینک مقصد هنگام کلیک', verbose_name='لینک تبلیغ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_at', models.DateTimeField(blank=True, help_text='تاریخ و ساعت شروع نمایش (اختیاری)', null=True, verbose_name='شروع نمایش')),
                ('end_at', models.DateTimeField(blank=True, help_text='تاریخ و ساعت پایان نمایش (اختیاری)', null=True, verbose_name='پایان نمایش')),
                ('priority', models.IntegerField(default=0, help_text='تبلیغات با اولویت بالاتر ابتدا نمایش داده می\u200cشوند', verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_admins', to='classes.faculty', verbose_name='دانشکده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل ادمین دانشکده',
                'verbose_name_plural': 'پروفایل\u200cهای ادمین دانشکده',
            },
        ),
        migrations.CreateModel(
            name='AdTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'نمایش'), ('click', 'کلیک')], max_length=20, verbose_name='نوع رویداد')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='classes.ad', verbose_name='تبلیغ')),
            ],
            options={
                'verbose_name': 'ردیابی تبلیغ',
                'verbose_name_plural': 'ردیابی تبلیغات',
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_active', 'priority'], name='classes_ad_is_acti_61f876_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['start_at', 'end_at'], name='classes_ad_start_a_d10355_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyadminprofile',
            index=models.Index(fields=['user'], name='classes_fac_user_id_6d210b_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyadminprofile',
            index=models.Index(fields=['faculty'], name='classes_fac_faculty_a6ac8e_idx'),
        ),
        migrations.AddIndex(
            model_name='adtracking',
            index=models.Index(fields=['ad', 'event_type', 'date'], name='classes_adt_ad_id_52f1d8_idx'),
        ),
        migrations.AddIndex(
            model_name='adtracking',
            index=models.Index(fields=['date'], name='classes_adt_date_33943b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adtracking',
            unique_together={('ad', 'event_type', 'date')},
        ),
    ]
