# Generated by Django 4.2.24 on 2025-11-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_cleanup_vote_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='cancelled_until',
            field=models.DateTimeField(blank=True, help_text='اگر تنظیم شود، کلاس تا این زمان لغو محسوب می\u200cشود و سپس خودکار بازنشانی می\u200cگردد', null=True, verbose_name='لغو تا'),
        ),
        migrations.CreateModel(
            name='ScheduleFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_holding', 'کلاس برگزار نمی\u200cشود'), ('data_wrong', 'اطلاعات کلاس اشتباه است')], max_length=32, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دانشجو')),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP گزارش\u200cدهنده')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('seen', 'دیده شده'), ('resolved', 'حل شده')], default='new', max_length=16, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='classes.faculty', verbose_name='دانشکده')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='classes.classschedule', verbose_name='برنامه کلاسی')),
            ],
            options={
                'verbose_name': 'گزارش دانشجویی',
                'verbose_name_plural': 'گزارش\u200cهای دانشجویی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['faculty', 'status'], name='classes_sch_faculty_d09bd8_idx'), models.Index(fields=['schedule', 'status'], name='classes_sch_schedul_6ca100_idx')],
            },
        ),
    ]
