# Generated by Django 4.2.24 on 2025-11-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_classschedule_cancelled_until_scheduleflag'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheduleflag',
            name='classes_sch_faculty_d09bd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleflag',
            name='classes_sch_schedul_6ca100_idx',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='cancelled_until',
        ),
        migrations.RemoveField(
            model_name='scheduleflag',
            name='status',
        ),
        migrations.RemoveField(
            model_name='scheduleflag',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='scheduleflag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='scheduleflag',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیح دانشجو'),
        ),
        migrations.AlterField(
            model_name='scheduleflag',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_flags', to='classes.faculty', verbose_name='دانشکده'),
        ),
        migrations.AlterField(
            model_name='scheduleflag',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='classes.classschedule', verbose_name='کلاس'),
        ),
        migrations.AddIndex(
            model_name='scheduleflag',
            index=models.Index(fields=['faculty', 'created_at'], name='classes_sch_faculty_7b355f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleflag',
            index=models.Index(fields=['schedule', 'created_at'], name='classes_sch_schedul_835d2f_idx'),
        ),
    ]
